# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Metabolism of Microbial Communities @ TU Delft
email: D.Bajic@tudelft.nl
tagline: Website of the Metabolism of Microbial Communities group at TU Delft
description: This is the webpage of the Metabolism of Microbial Communities group at TU Delft. Here you will find information about our research, teaching, latest news, and contact details.  
baseurl: 
url: "https://djbajic.github.io"

# other info
twitter_username: metaboli3am
github_username: djbajic
scholar_username: "6tfrMqYAAAAJ"
resgate_username: "Djordje-Bajic"
orcid_username: "0000-0002-6716-7898"
linkedin_username: "djordje-bajić-6591a217"
maplocation: Faculty of Applied Sciences, TU Delft. 
author: "Djordje Bajić"


map_latitude: 51.99145374035248
map_longitude: 4.3824941063469
map_title: 'Faculty of Applied Sciences - TU Delft'
#map_apikey: "AIzaSyD3OqSEPg5iyHcriIfz-776IahCE3DhxZY"

include:
  - .htaccess
  - _pages




sass:
  sass_dir: _sass

# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false



# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false
  parse_block_html: true # default for kramdown is false. This will enable using Markdown links
